extends RefCounted

const PATHS: PackedStringArray = [
	"res://Assets/Soundboard/solo-clap.wav",
	"res://Assets/Soundboard/wolf-whistle.wav",
	"res://Assets/Soundboard/Bright Female/01-bye.wav",
	"res://Assets/Soundboard/Bright Female/01-how are you.wav",
	"res://Assets/Soundboard/Bright Female/01-i love you (confession).wav",
	"res://Assets/Soundboard/Bright Female/01-i'm good thank you.wav",
	"res://Assets/Soundboard/Bright Female/02-good morning.wav",
	"res://Assets/Soundboard/Bright Female/02-goodbye.wav",
	"res://Assets/Soundboard/Bright Female/02-hello.wav",
	"res://Assets/Soundboard/Bright Female/02-how.wav",
	"res://Assets/Soundboard/Bright Female/02-how are you.wav",
	"res://Assets/Soundboard/Bright Female/03-i don't wanna talk right now.wav",
	"res://Assets/Soundboard/Bright Female/03-see ya later.wav",
	"res://Assets/Soundboard/Bright Female/03-thank you.wav",
	"res://Assets/Soundboard/Bright Female/03-what.wav",
	"res://Assets/Soundboard/custom/yapidar.mp3",
	"res://Assets/Soundboard/custom/yebiwe.mp3",
	"res://Assets/Soundboard/Mature Female/how3.wav",
	"res://Assets/Soundboard/Mature Female/text_me.wav",
	"res://Assets/Soundboard/Mature Female/what3.wav",
	"res://Assets/Soundboard/Mature Female/why3.wav",
]
