extends RefCounted

const PATHS: PackedStringArray = [
	"res://Assets/Soundboard/drama-1.mp3",
	"res://Assets/Soundboard/drama-2.mp3",
	"res://Assets/Soundboard/movie-ending-meme-to-be-continued-directed-by.mp3",
	"res://Assets/Soundboard/nico-nico.mp3",
	"res://Assets/Soundboard/tuturu.mp3",
	"res://Assets/Soundboard/tutututu-meme-demotivator.mp3",
	"res://Assets/Soundboard/ua/20.31 Годжу Сатору прибув.mp3",
	"res://Assets/Soundboard/ua/Андрію, я не вірю своїм окулярам, це ти.mp3",
	"res://Assets/Soundboard/ua/Бачиш по всьому світу розкидано так багато огидних людей.mp3",
	"res://Assets/Soundboard/ua/Він шо лорд, сер, пер, хер.mp3",
	"res://Assets/Soundboard/ua/Висунуті члени.mp3",
	"res://Assets/Soundboard/ua/Гоп стоп поворот, їдемо на белгород.mp3",
	"res://Assets/Soundboard/ua/Діставай свою шаблю, козаче.mp3",
	"res://Assets/Soundboard/ua/Давай по новой, міша, всьо хуйня.mp3",
	"res://Assets/Soundboard/ua/КОКОНАТО СІ.mp3",
	"res://Assets/Soundboard/ua/Коля где твоя аскорбиночка.mp3",
	"res://Assets/Soundboard/ua/Ну за який хуй ти його купив!.mp3",
	"res://Assets/Soundboard/ua/Я мільйонер! а не, я бедний....mp3",
	"res://Assets/Soundboard/pl/polish-cow-couped-mp3cut_fhCitWB.mp3",
	"res://Assets/Soundboard/pl/spierdalai.mp3",
	"res://Assets/Soundboard/pl/worms-do-zobaczenia.mp3",
	"res://Assets/Soundboard/pl/worms-dobry-poczatek.mp3",
	"res://Assets/Soundboard/pl/worms-genialnie.mp3",
	"res://Assets/Soundboard/pl/worms-idiota-pl.mp3",
	"res://Assets/Soundboard/pl/worms-zdrajca.mp3",
	"res://Assets/Soundboard/ru/casino.mp3",
	"res://Assets/Soundboard/ru/come-on-new-bear.mp3",
	"res://Assets/Soundboard/ru/damn-why-did-i-come-here.mp3",
	"res://Assets/Soundboard/ru/here-our-powers-are-all.mp3",
	"res://Assets/Soundboard/ru/live-and-have-enough.mp3",
	"res://Assets/Soundboard/ru/run.mp3",
	"res://Assets/Soundboard/ru/there-is-a-penetration.mp3",
	"res://Assets/Soundboard/ru/yapidar.mp3",
	"res://Assets/Soundboard/ru/yebiwe.mp3",
	"res://Assets/Soundboard/en/no-god-please-no.mp3",
	"res://Assets/Soundboard/en/this-is-sparta.mp3",
	"res://Assets/Soundboard/kz/1.mp3",
	"res://Assets/Soundboard/kz/hello.mp3",
	"res://Assets/Soundboard/by/53341-lukashenko-menja-rasstreljali-na-vostochnoi-granic.mp3",
	"res://Assets/Soundboard/by/ne-ponimaju.mp3",
	"res://Assets/Soundboard/by/normalno.mp3",
	"res://Assets/Soundboard/by/ploho.mp3",
]
