[Service]
ExecStart=
ExecStart=/opt/project-joker-server/godot-full --headless --main-pack /opt/project-joker-server/project-joker-server.pck res://Scenes/DedicatedServer.tscn -- --port=8765 --account-db=/var/lib/project-joker-server/accounts.json --match-db=/var/lib/project-joker-server/matches.json
